name: Node

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: check API Types
        run: |
          yarn --cwd api install --frozen-lockfile && yarn --cwd api tsc
        env:
          CI: true

      - name: Publish Docker Client
        uses: elgohr/Publish-Docker-Github-Action@1.13
        with:
          name: pabloszx/awesome-templates-client
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: client
          cache: true
      - name: Publish Docker API
        uses: elgohr/Publish-Docker-Github-Action@1.13
        with:
          name: pabloszx/awesome-templates-api
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: api
          cache: true
