name: Node

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: build
        run: |
          yarn --cwd api install --frozen-lockfile && yarn --cwd api tsc
          yarn --cwd client install --frozen-lockfile && yarn --cwd client build
        env:
          CI: true
